[package]
name = "daqingest"
version = "0.1.3"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2021"

[lib]
path = "src/daqingest.rs"

[[bin]]
name = "daqingest"
path = "src/bin/daqingest.rs"

[dependencies]
clap = { version = "4.0.22", features = ["derive", "cargo"] }
tokio = { version = "1.23.0", features = ["rt-multi-thread", "io-util", "net", "time", "sync", "fs", "tracing"] }
tracing = "0.1.37"
futures-util = "0.3"
async-channel = "1.6"
chrono = "0.4"
bytes = "1.1"
scylla = "0.7"
serde = { version = "1.0", features = ["derive"] }
err = { path = "../../daqbuffer/err" }
log = { path = "../log" }
netpod = { path = "../../daqbuffer/netpod" }
netfetch = { path = "../netfetch" }
taskrun = { path = "../../daqbuffer/taskrun" }
