[package]
name = "daqingest"
version = "0.1.0"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2021"

[lib]
path = "src/daqingest.rs"

[[bin]]
name = "daqingest"
path = "src/bin/daqingest.rs"

[dependencies]
clap = { version = "3", features = ["derive", "cargo"] }
chrono = "0.4"
bytes = "1.1"
scylla = "0.4"
err = { path = "../../daqbuffer/err" }
taskrun = { path = "../../daqbuffer/taskrun" }
netfetch = { path = "../netfetch" }
