[workspace]
members = ["log", "netfetch", "daqingest"]

[profile.release]
opt-level = 1
debug = 0
overflow-checks = false
debug-assertions = false
lto = false
codegen-units = 32
incremental = true

[patch.crates-io]
tokio = { git = "https://github.com/dominikwerder/tokio", rev = "995221d8" }
