[workspace]
members = ["log", "netfetch", "daqingest"]

[profile.release]
opt-level = 2
debug = 1
overflow-checks = false
debug-assertions = false
lto = "thin"
codegen-units = 32
incremental = true

[patch.crates-io]
#tokio = { git = "https://github.com/dominikwerder/tokio", rev = "995221d8" }
