[package]
name = "batchtools"
version = "0.0.1"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2021"

[dependencies]
log = { path = "../log" }
err = { path = "../../daqbuffer/crates/err" }
taskrun = { path = "../../daqbuffer/crates/taskrun" }
async-channel = "1.9.0"
