[package]
name = "stats_proc"
version = "0.0.1"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2021"

[lib]
path = "src/stats_proc.rs"
proc-macro = true

[dependencies]
stats_types = { path = "../stats_types" }
syn = "1"
quote = "1"
