name: build-daqingest-rhel7
# on:
#   repository_dispatch:
#     types:
#       - trigger_build
on: workflow_dispatch
jobs:
  build-daqbuffer-job:
    runs-on: ubuntu-latest
    container:
      image: ugnvc/psi:daqbuild01
      env:
        PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        RUSTUP_HOME: /root/.rustup
        CARGO_HOME: /root/.cargo
    steps:
      - uses: actions/checkout@v3
      - run: echo $HOME
      - run: echo $PATH
      - run: echo $GITHUB_WORKSPACE
      - run: /usr/bin/df -h
      - run: id
      - run: pwd
      - run: ls -la
      - run: ls -la /
      - run: ls -la /github
      - run: ls -la /github/home
      - run: ls -la /github/workflow
      - run: cat /github/workflow/event.json
      - run: ls -la /root
      - run: source /root/.cargo/env
      - run: echo "$HOME"
      - run: echo "$PATH"
      - run: /bin/bash -c 'PATH=/root/.cargo/bin && echo "$PATH"'
      - run: /bin/bash -c 'PATH=/root/.cargo/bin && cargo --version'
      - run: /bin/bash -c 'PATH=/root/.cargo/bin && rustc --version'
      - run: rustc --version
      - run: cargo --version
      - run: pwd
      - run: cd $GITHUB_WORKSPACE
      - run: pwd
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: daqbufferbin
      #     path: target/release/daqbuffer
