name: build-daqingest-rhel7
# on:
#   repository_dispatch:
#     types:
#       - trigger_build
# on: workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      flags:
        description: Additional flags
        default: ""
        required: false
        deprecationMessage: Not supported
      # debug:
      #   description: Debug symbols
      #   type: choice
      #   options:
      #     - Simple
      #     - Detailed
      #   default: Detailed
      # release:
      #   description: Package
      #   type: boolean
      #   default: true
      # other:
      #   description: Other
      #   type: environment
      #   required: false
jobs:
  build-daqbuffer-job:
    runs-on: ubuntu-latest
    container:
      image: ugnvc/psi:daqbuild01
      # credentials:
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.github_token }}
      env:
        PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        RUSTUP_HOME: /root/.rustup
        CARGO_HOME: /root/.cargo
      # ports:
      #   - 3456
    steps:
      # - uses: actions/checkout@v3
      # - run: "echo Flags: ${{ github.event.inputs.flags }}"
      # - run: echo $HOME
      # - run: echo $PATH
      # - run: echo $GITHUB_WORKSPACE
      # - run: /usr/bin/df -h
      # - run: id
      # - run: pwd
      - run: find /github -type f
      - run: cat /github/workflow/event.json
      - run: ls -la /root
      - run: rustc --version
      - run: cargo --version
      - run: mkdir /build
      - run: git clone https://github.com/paulscherrerinstitute/daqingest.git
        working-directory: /build
      - run: git checkout dev
        working-directory: /build/daqingest
      - run: cargo build
        working-directory: /build/daqingest

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: daqbufferbin
      #     path: target/release/daqbuffer
