name: build-daqingest-rhel7
on:
  push:
    tags:
      - buildaction
  workflow_dispatch:
    inputs:
      flags:
        description: Additional flags
        default: ""
        required: false
        deprecationMessage: Not supported
      # debug:
      #   description: Debug symbols
      #   type: choice
      #   options:
      #     - Simple
      #     - Detailed
      #   default: Detailed
      # release:
      #   description: Package
      #   type: boolean
      #   default: true
      # other:
      #   description: Other
      #   type: environment
      #   required: false
jobs:
  build-daqbuffer-job:
    runs-on: ubuntu-latest
    container:
      image: ugnvc/psi:daqbuild.0.0.1
      # credentials:
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.github_token }}
      env:
        PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        RUSTUP_HOME: /root/.rustup
        CARGO_HOME: /root/.cargo
      # ports:
      #   - 3456
    steps:
      # - run: find /github -type f
      # - run: cat /github/workflow/event.json
      # - run: ls -la /root
      - run: ls -la /
      - run: ls -la /__w
      - run: ls -la /home/runner
      - run: ls -la /home/runner/work
      - run: git --version
      - run: rustc --version
      - run: cargo --version
      - run: mkdir /build
      # - run: "echo Flags: ${{ github.event.inputs.flags }}"
      # - run: echo $HOME
      # - run: echo $PATH
      # - run: echo $GITHUB_WORKSPACE
      # - run: /usr/bin/df -h
      # - run: id
      # - run: pwd
      - run: echo GITHUB_WORKSPACE "$GITHUB_WORKSPACE"
      - run: echo RUNNER_WORKSPACE "$RUNNER_WORKSPACE"
      - run: echo github.workspace ${{github.workspace}}
      - run: echo runner.workspace ${{runner.workspace}}
      - run: echo "gh=$GITHUB_WORKSPACE" >> "$GITHUB_OUTPUT"
        id: wdset
      - run: find "$GITHUB_WORKSPACE"
      # - uses: actions/checkout@v4
      #   with:
      #     repository: paulscherrerinstitute/daqbuffer.git
      #     ref: dev
      #     path: build
      # - uses: actions/checkout@v4
      #   with:
      #     repository: paulscherrerinstitute/daqingest.git
      #     path: build
      - run: git clone --branch dev https://github.com/paulscherrerinstitute/daqbuffer.git
        working-directory: ${{steps.wdset.gh}}/build
      - run: git clone --branch dev https://github.com/paulscherrerinstitute/daqingest.git
        working-directory: ${{steps.wdset.gh}}/build
      - run: ls -la $GITHUB_WORKSPACE
      - run: find $GITHUB_WORKSPACE -type f -and \( -name \*.rs -or -name \*.toml \)
      - run: find ${{steps.wdset.gh}} -type f -and \( -name \*.rs -or -name \*.toml \)
        working-directory: ${{steps.wdset.gh}}/build
      - run: cargo build --release
        working-directory: ${{steps.wdset.gh}}/build/daqingest
      - run: ls -l
        working-directory: ${{steps.wdset.gh}}/build/daqingest/target/release
      - run: ./daqingest --version
        working-directory: ${{steps.wdset.gh}}/build/daqingest/target/release
      - run: echo "daqingest_version=$(./daqingest --version)" >> "$GITHUB_OUTPUT"
        id: daqingest_version_set
        working-directory: ${{steps.wdset.gh}}/build/daqingest/target/release
      - uses: actions/upload-artifact@v3
        with:
          name: daqingest-${{ steps.daqingest_version_set.outputs.daqingest_version }}-amd64-rhel7
          path: ${{steps.wdset.gh}}/build/daqingest/target/release/daqingest
      - run: curl -o rel.json -L \
          -H accept:application/vnd.github+json \
          -H authorization:Bearer\\ ${{secrets.github_token}} \
          -H X-GitHub-Api-Version:\\ 2022-11-28 \
          https://api.github.com/repos/paulscherrerinstitut/daqingest/releases
      - run: cat rel.json
